### ISSUE TITLE
Analisis de App

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-irving-1#1]
[App RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-irving-1/files/14315234/App.RA.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by magaly1311** [comment]
Excelente : 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
